# config.yaml

# Select paths to data and output directories
data_dir: "/mnt/seaes01-data01/nixon-microbiome/shared/bioinformatic_toolkit/symlink_staging" # Directory with input raw FASTQ data, NOTE - dont end the filepath with a "/"

# Select analyses
# Type true or false for the analysis you want. IMPORTANT - "assemble" needs to be run first for all other sub analyses to work
sub_analyses:
  assemble: true
  mags: false #needs testing
  kaiju: true
  tpm: false
  viruses: false #not yet functional 
  bgc: false

#Select threads used
max_threads: 20  # Max threads per rule

#Select samples used (THESE NEED TO BE ZIPPED FASTA FILES (.fasta.gz))
samples:
  - F1
  - F2
  - F3
  - N1
  - N2
  - N3
  - O1
  - O2
  - O3
  - O4

# Add more sample names as needed

#Do not change
output_dir: "/mnt/seaes01-data01/nixon-microbiome/shared/bioinformatic_toolkit/output_repository" 
containers_dir: "/mnt/seaes01-data01/nixon-microbiome/containers"
