#!/bin/bash --login
#$ -cwd             # Job will run from the current directory
#$ -pe smp.pe 15
#$ -N snakemake    	# Give the job a name
#$ -m bea	    	# Email on start, end or abort
#$ -M christopher.stead@manchester.ac.uk

# Set paths
export APPTAINER_HOME=$HOME
export APPTAINER_BINDPATH=/mnt
export APPTAINER_BIND=/mnt
export APPTAINER=/mnt
export GTDBTK_DATA_PATH="/mnt/seaes01-data01/nixon-microbiome/databases/gtdbtk_data/release220"
export MPLCONFIGDIR=/mnt/seaes01-data01/nixon-microbiome/shared/bioinformatic_toolkit/output_repository/antimash_temp
#export LC_ALL=C.UTF-8
#export LANG=C.UTF-8
export GENOMAD_DB=/mnt/data/genomad_db_v1.7

#run snakemake and apptainer
module load apps/gcc/apptainer/1.0.3
module load apps/python/miniconda3/4.10.3
source activate snakemake

snakemake  --cores $NSLOTS --max-threads $NSLOTS --rerun-incomplete --use-singularity --configfile config.yaml -s Snakefile
