# config.yaml
# Select analyses
# Type true or false for the analysis you want. IMPORTANT - 
# "assemble" needs to be run first for all other sub analyses to work
sub_analyses:
  assemble: false
  assemble_megahit: true
  mags: true
  mags_euk: false
  kaiju: true
  kaiju_only: false
  tpm: false
  tpm_1: true
  tpm_high_diversity: false
  viruses: false
  bgc: true
  diversity: true
  metabolic: true
  s3_abundance: true
  mobilome: true
#Select threads used
max_threads: 15

#Select samples used. This will be the name of your symlink file, the 
#forward and reverse reads ending in  _1.fastq.gz and _2.fastq.gz respectively
samples:
  - GDE27AAK
#  - GDE29AAK
#  - GDE31AAK
#  - GDE33AAK
#  - GDE35AAK
#  -
#  -
#  -
#  -
#  - 
# Add more sample names as needed

#Do not change
# Select paths to data and output directories
data_dir: "/mnt/seaes01-data01/nixon-microbiome/shared/bioinformatic_toolkit/symlink_staging"
output_dir: "/mnt/seaes01-data01/nixon-microbiome/shared/bioinformatic_toolkit/output_repository_snaedis_mat"
containers_dir: "/mnt/seaes01-data01/nixon-microbiome/containers"
benchmark_dir: "/mnt/seaes01-data01/nixon-microbiome/shared/bioinformatic_toolkit/benchmarks/snaedis_mat"
min_contig_len: 1000
