# Load the configuration file
configfile: "config.yaml"

# Globals
SAMPLES = config["samples"]
OUTPUT_DIR = config["output_dir"]
CONTAINERS_DIR = config["containers_dir"]
MAX_THREADS = config["max_threads"]

# Conditional imports for each sub-analysis
if config["sub_analyses"].get("assemble", False):
    include: "assemble.smk"
if config["sub_analyses"].get("mags", False):
    include: "mags.smk"
if config["sub_analyses"].get("kaiju", False):
    include: "kaiju.smk"
if config["sub_analyses"].get("tpm", False):
    include: "tpm.smk"
if config["sub_analyses"].get("viruses", False):
    include: "viruses.smk"
if config["sub_analyses"].get("bgc", False):
    include: "bgc.smk"

# Rule to combine all final outputs from each sub-analysis
rule all:
	input:
		# Outputs for "assemble"
		expand(f"{OUTPUT_DIR}/{{sample}}_forward_paired.fq", sample=SAMPLES),
		expand(f"{OUTPUT_DIR}/{{sample}}_reverse_paired.fq", sample=SAMPLES),
		expand(f"{OUTPUT_DIR}/{{sample}}_fastqc/", sample=SAMPLES),
		expand(f"{OUTPUT_DIR}/{{sample}}_assembly", sample=SAMPLES),
		expand(f"{OUTPUT_DIR}/{{sample}}_prokka/{{sample}}_annotated.gff", sample=SAMPLES),
		expand(f"{OUTPUT_DIR}/{{sample}}_prokka/{{sample}}_annotated.tsv", sample=SAMPLES),
		expand(f"{OUTPUT_DIR}/{{sample}}_prokka/{{sample}}_annotated.faa", sample=SAMPLES), 
		expand(f"{OUTPUT_DIR}/{{sample}}_quast_report", sample=SAMPLES),
		# Conditional outputs for other sub-analyses
		expand(f"{OUTPUT_DIR}/{{sample}}_mags_bins", sample=SAMPLES) if config["sub_analyses"].get("mags", False) else [],
		expand(f"{OUTPUT_DIR}/{{sample}}_kaiju_results.txt", sample=SAMPLES) if config["sub_analyses"].get("kaiju", False) else [],
		expand(f"{OUTPUT_DIR}/{{sample}}_tpm_annotated.txt", sample=SAMPLES) if config["sub_analyses"].get("tpm", False) else [],
		expand(f"{OUTPUT_DIR}/{{sample}}_genomad_viral_annotations.gff", sample=SAMPLES) if config["sub_analyses"].get("viruses", False) else [],
		expand(f"{OUTPUT_DIR}/{{sample}}_antismash_bgc.gbk", sample=SAMPLES) if config["sub_analyses"].get("bgc", False) else []
